version: '3.8'

services:
  mongo-seed:
    depends_on:
      - mongo
    volumes:
      - ./mongo-seed/dump:/var/dump
    command:
      mongorestore
    
  api:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-server
    restart: always
    env_file: .env
    ports:
      - $PORT:3000
  mongo:
    image: mongo
    ports:
      - 3456:27017
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - mongo_data:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  mysqldb:
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - 7890:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=ok
      - MYSQL_DATABASE=mi_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=mi_user
      - MYSQL_PASSWORD=1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
volumes:
  mongo_data:
  mysql_data: